# au_poivre_recipe.py

def au_poivre_recipe():
    print("Au Poivre Sauce Recipe:\n")
    print("Ingredients:\n")
    print("  * 2 tablespoons butter\n")
    print("  * 1/4 cup finely chopped shallots\n")
    print("  * 2 cloves garlic, minced\n")
    print("  * 2 tablespoons black peppercorns, coarsely crushed\n")
    print("  * 1/4 cup brandy (or cognac)\n")
    print("  * 1 cup beef broth\n")
    print("  * 1/2 cup heavy cream\n")
    print("  * 1 tablespoon Dijon mustard\n")
    print("  * Salt to taste\n")
    print("Instructions:\n")
    print("  1. Melt butter in a saucepan over medium heat.\n")
    print("  2. Add shallots and garlic and cook until softened, about 2-3 minutes.\n")
    print("  3. Stir in crushed peppercorns and cook for 1 minute.\n")
    print("  4. Pour in brandy (or cognac) and carefully ignite it. Let the alcohol burn off.\n")
    print("  5. Add beef broth and bring to a simmer. Cook until reduced by half, about 5-7 minutes.\n")
    print("  6. Stir in heavy cream and Dijon mustard. Season with salt to taste.\n")
    print("  7. Simmer for another 2-3 minutes, or until the sauce has thickened slightly.\n")
    print("  8. Serve immediately over steak or other grilled meats.\n")

au_poivre_recipe()
